sudo: required
services:
  - docker
language: python

before_install:
  - docker-compose build
  - docker-compose pull

python:
  - "2.7"

script:
  - docker-compose run get_plaws
  - ls
  - sudo python testing/random_select.py
  - docker-compose run congress_scrape
