plaw_scrapy_vol:
  #image: trcook/plaw_scraper
  #  swap comments on image and build to get docker-compose to build instead of download
  build: ./plaw_scraper
  name: cong_scraper_volume



get_plaws:
  image: trcook/docker-scrapy
  # swap comments on image and build to get docker-compose to build instead of download
  #build: ./docker-scrapy
  volumes:
    - ./data:/data
  volumes_from:
    - plaw_scrapy_vol
  working_dir: /scrapy/
  command: ["scrapy", "crawl", "plaw", "-o", "/data/plaws.csv"]


congress_scrape:
  image: trcook/congress
  # swap comments on image and build to get docker-compose to build instead of download
  #build: ./docker-congress
  volumes:
    - ./data:/congress
  command: ["bill_info_batch", "--file_input=./plaws.csv"]
